/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Productos;

import SQL.Sentencias_sql;

import javax.swing.JOptionPane;

/**
 *
 * @author comol
 */
public class Pantalla_agregar_productos extends javax.swing.JFrame 
{
     Sentencias_sql sen = new Sentencias_sql();

     
    public Pantalla_agregar_productos() 
    {
        initComponents();
        limpiar();
        bloquear_cajas();
        comboProveedor();
        setBounds(40,200,750,195);
        setResizable(false);
        setVisible(true);
    }
    
    
public void comboProveedor()
{
    String tabla,campo;
    tabla="Proveedores";
    campo="Empresa";
    Object[] tipo = sen.poblar_combox(tabla,campo,2,true);
    combo_ID_Proveedor.removeAllItems();
    for(int i=0;i<tipo.length;i++)
    {
        combo_ID_Proveedor.addItem(tipo[i]);
        System.out.println(tipo[1]);
    }   
}

public void limpiar()
    {
       codigo_producto.setText("");
       descripcion_producto.setText("");
       presentacion_producto.setText("");
       combo_ID_Proveedor.setName("");
       precio_unitario_compra.setText("");
       precio_unitario_venta.setText("");
    }
    
    public void  bloquear_cajas()
    {
       codigo_producto.setEnabled(false);
       descripcion_producto.setEnabled(false);
       presentacion_producto.setEnabled(false);
       combo_ID_Proveedor.setEnabled(false);
       precio_unitario_compra.setEnabled(false);
       precio_unitario_venta.setEnabled(false);
       registrar.setEnabled(false);
       cancelar.setEnabled(false);      
       nuevoregistro.setEnabled(true);
    }
    public void  desbloquear()
    {
       codigo_producto.setEnabled(true);
       descripcion_producto.setEnabled(true);
       presentacion_producto.setEnabled(true);
       combo_ID_Proveedor.setEnabled(true);
       precio_unitario_compra.setEnabled(true);
       precio_unitario_venta.setEnabled(true);
       registrar.setEnabled(true);
       cancelar.setEnabled(true);      
       nuevoregistro.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descripcion_producto = new javax.swing.JTextField();
        presentacion_producto = new javax.swing.JTextField();
        combo_ID_Proveedor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        nuevoregistro = new javax.swing.JButton();
        precio_unitario_compra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        codigo_producto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        precio_unitario_venta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setTitle("Registrar producto");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descripcion_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcion_productoActionPerformed(evt);
            }
        });
        getContentPane().add(descripcion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 380, -1));

        presentacion_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentacion_productoActionPerformed(evt);
            }
        });
        getContentPane().add(presentacion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 158, -1));

        combo_ID_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ID_ProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(combo_ID_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, -1));

        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel3.setText("Presentacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jLabel6.setText("Proveedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 110, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 110, -1));

        nuevoregistro.setText("Nuevo registro");
        nuevoregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoregistroActionPerformed(evt);
            }
        });
        getContentPane().add(nuevoregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, -1));

        precio_unitario_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_unitario_compraActionPerformed(evt);
            }
        });
        getContentPane().add(precio_unitario_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 158, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Precio Unitario de Compra");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 160, -1));

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 170, -1));
        getContentPane().add(codigo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 174, -1));

        jLabel9.setText("Codigo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        getContentPane().add(precio_unitario_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 158, -1));

        jLabel10.setText("Precio Unitario de Venta");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcion_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcion_productoActionPerformed
        descripcion_producto.transferFocus();
    }//GEN-LAST:event_descripcion_productoActionPerformed

    private void presentacion_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentacion_productoActionPerformed
        presentacion_producto.transferFocus();
    }//GEN-LAST:event_presentacion_productoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        bloquear_cajas();
        limpiar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void nuevoregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoregistroActionPerformed
        desbloquear();
        codigo_producto.requestFocus();
    }//GEN-LAST:event_nuevoregistroActionPerformed

    private void precio_unitario_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_unitario_compraActionPerformed
        precio_unitario_compra.transferFocus();
    }//GEN-LAST:event_precio_unitario_compraActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        try
        {
            String codigo,descripcion,presentacion,id_proveedor,existencias,PrecioCompra,PrecioVenta;
            int longitud_prooveedor=0;
            
            codigo = codigo_producto.getText();
            longitud_prooveedor = combo_ID_Proveedor.getSelectedItem().toString().length();
            descripcion = descripcion_producto.getText();
            presentacion = presentacion_producto.getText();
            id_proveedor=combo_ID_Proveedor.getSelectedItem().toString().substring(longitud_prooveedor - 5, longitud_prooveedor - 1);
            System.out.println(id_proveedor);
            PrecioCompra =  precio_unitario_compra.getText();
            PrecioVenta =  precio_unitario_venta.getText();
        
            ControlProductos control = new ControlProductos();
        if(!codigo.equals("") && !descripcion.equals("") && !presentacion.equals(""))
        {
            if(control.agregarProductos(codigo,descripcion,presentacion,id_proveedor,PrecioCompra,PrecioVenta))
            {
                JOptionPane.showMessageDialog(null,"El producto se registro con exito");
                limpiar();
                bloquear_cajas();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error al registrar el producto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Hay campos obligatorios");
        }
         
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null,"Datos ingresados no validos","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void combo_ID_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ID_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ID_ProveedorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo_producto;
    private javax.swing.JComboBox combo_ID_Proveedor;
    private javax.swing.JTextField descripcion_producto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nuevoregistro;
    private javax.swing.JTextField precio_unitario_compra;
    private javax.swing.JTextField precio_unitario_venta;
    private javax.swing.JTextField presentacion_producto;
    private javax.swing.JButton registrar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
